AWSTemplateFormatVersion: "2010-09-09"
Description: FIS experiments template
Parameters:
  ClusterName:
    Type: String
    Description: Cluster Name.
Resources:
  FISLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: 'fis-log-group'
  FISExperiment:
    Type: AWS::FIS::ExperimentTemplate
    Properties:
      Description: A Fault Injection Simulator experiment for testing spot-instance-interruptions .
      Actions: 
        spotInstanceinterruption:
          ActionId: 'aws:ec2:send-spot-instance-interruptions'
          Parameters: 
            durationBeforeInterruption: 'PT2M'
          Targets:
            SpotInstances: spotInTargetCluster
      Targets:
        spotInTargetCluster:
          ResourceTags:
            aws:eks:cluster-name : !Sub '${ClusterName}'
          ResourceType: 'aws:ec2:spot-instance'
          SelectionMode: ALL   
      RoleArn: !GetAtt FISRole.Arn
      StopConditions:
        - Source: 'none'
      Tags: 
        Name: !Sub 'SpotInterruptionTest-${ClusterName}'
      LogConfiguration:
        LogSchemaVersion: 1
        CloudWatchLogsConfiguration:
          LogGroupArn: !GetAtt FISLogGroup.Arn
  FISRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal:
              Service: 'fis.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::aws:policy/service-role/AWSFaultInjectionSimulatorEC2Access"
      Policies:
      - PolicyName: FISCloudWatch
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - logs:PutLogEvents
              - logs:CreateLogDelivery
              Resource: '*'
