AWSTemplateFormatVersion: "2010-09-09"
Description: Resources used by https://github.com/aws/karpenter
Parameters:
  ClusterName:
    Type: String
    Description: Cluster Name.
Resources:
  FisExperiment:
    Type: AWS::FIS::ExperimentTemplate
    Properties:
      Description: A Fault Injection Simulator experiment for testing spot-instance-interruptions .
      Targets:
        spotInTargetCluster:
          ResourceTags:
            'aws:eks:cluster-name': !Sub '${ClusterName}'
          ResourceType: 'aws:ec2:instance'
      Actions: 
        spotInstanceinterruption:
          ActionId: 'aws:ec2:send-spot-instance-interruptions'
          Parameters: 
            durationBeforeInterruption: 'PT2M'
          Targets:
            Instances: spotInTargetCluster    
      RoleArn: !GetAtt FISRole.Arn
      StopConditions:
        - Source: 'none'
      Tags: 
        Name: 'SpotInterruptionTest'
  FISRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal:
              Service: 'fis.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::aws:policy/service-role/AWSFaultInjectionSimulatorEC2Access"